---
title: "Monona_Residence_Time"
output: html_document
---

```{r}
library(lubridate)
library(tidyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r}
#Residence time check for Monona using Yahara discharge from Windsor USGS gage location with adjusted values accounting for other inflows from 1989-10-01 00:00:00 through 2016-12-31 23:00:00.
rm(list = ls())

setwd("C:/Users/linne/OneDrive/Documents/GLM955-South/monona/LAR")

discharge <- read_csv("MO_Yahara_flow.csv")
discharge$FLOW <- discharge$FLOW/(3600*24)

write_csv(discharge, "MO_Yahara_flow.csv")

volume <- 111520000  #in m^3 (value from LTER website)

discharge1 <- discharge %>%
  group_by(year = year(time)) %>%
  summarise(total.flow = sum(FLOW))
#discharge1 has total discharge/year in m^3 for 1989-2016 *Note that 1989 only starts at Oct. 10.

discharge.compare <- discharge1 %>%
  mutate(residencetime = volume/(total.flow*3600*24)) #Residence time is in years 

z <- mean(discharge.compare$residencetime) #1.46
y<- sum(discharge.compare$residencetime) - 11.5892462

y/26

ggplot(discharge.compare) +
  geom_bar(aes(year, residencetime), stat = "identity") #Note that 1989 only starts at Oct. 10.
```

```{r}
discharge2 <- read_csv("MO_Yahara_flow.csv") %>%
  mutate(f = FLOW*2) %>%
  select(time, f, SALT, TEMP) %>%
  rename(FLOW = f)


discharge2 <- discharge2 %>%
  group_by(year = year(time)) %>%
  summarise(total.flow = sum(FLOW))

compare <- discharge2 %>%
  mutate(residencetime = volume/(total.flow*3600*24))

zz <- mean(compare$residencetime)
x<- sum(compare$residencetime) - 26.337684

x/26

ggplot(discharge.compare) +
  geom_bar(aes(year, residencetime), stat = "identity")
```
